import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { RiArrowDropDownLine } from "react-icons/ri";
import { RiSearch2Line } from "react-icons/ri";
import Navbar from "./components/Navbar";
import HomeBlog5 from "./components/HomeBlog5";
import HomeHighestBlogCategory from "./components/HomeHighestBlogCategory";
import RecentlyAddedBlogs from "./components/RecentlyAddedBlogs";
import HomeSecondHighestBlogCategory from "./components/HomeSecondHighestBlogCategory";
import HomeThirdHighestBlogCategory from "./components/HomeThirdHighestBlogCategory";
import HomeForthHighestBlogCategory from "./components/HomeForthHighestBlogCategory";
import Layout from "./components/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap"
          rel="stylesheet"
        />
        <link
          href="
https://cdn.jsdelivr.net/npm/icomoon@1.0.0/style.min.css
"
          rel="stylesheet"
        ></link>
      </Head>
      <>
        <Layout>
          {/* Start retroy layout blog posts */}
          {/* Top 5 blogs display */}
          <HomeBlog5 />
          {/* End retroy layout blog posts */}
          {/* Start posts-entry */}
          {/* Dispaly category that have highest number of blogs */}
          <HomeHighestBlogCategory />
          {/* End posts-entry */}
          {/* Start posts-entry */}
          {/* Dispaly 4 recently added blogs  */}
          <RecentlyAddedBlogs />
          {/* End posts-entry */}
          {/* Start posts-entry */}
          {/* This will display second highest blog cetgories */}
          <HomeSecondHighestBlogCategory />
          {/* This will display third highest category */}
          <HomeThirdHighestBlogCategory />
          {/* This will display forth highest category */}
          <HomeForthHighestBlogCategory />

          {/* Preloader */}
          {/* <Loader /> */}
        </Layout>
      </>
    </>
  );
}
